### ISSUE TITLE
Verify turning filter off turns heater off

### ISSUE THREAD

**Issue by rossdargan** [rossdargan/layz-spa-api#2]

**Comment by B-Hartley** [comment]
Yes, I've experimented with this.
Turning off power, turns off everything.
Turning off filter, also turns off heat.
Turning on filter, turns on power.
Turning on heat, turns on power and filter.

Hope that makes sense.

**Comment by B-Hartley** [comment]
I guess, turning on bubbles, turns on power, but I can't remember that I have ever checked.

**Comment by rossdargan** [comment]
Ace, so I don't need to do anything special then. I'll remove the code that does some of this as it must not be needed
